name: tool
publish_to: none
environment:
  sdk: '>2.11.0 <3.0.0'
dependencies:
  args: ^2.3.0
  charcode: ^1.3.1
  glob: ^2.0.2
  image: ^3.1.3
  markdown: ^5.0.0
  mime_type: ^1.0.0
  mustache_template: ^2.0.0
  path: ^1.8.1
  pool: ^1.5.0
  sass: ^1.51.0
  shelf: ^1.3.0
  string_scanner: ^1.1.0
